# Ruby
# Package your Ruby project.
# Add steps that install rails, analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/ruby

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseRubyVersion@0
  inputs:
    versionSpec: '>= 2.5'

- script: |
    TOKEN=ya29.GlsMB11CmVnpfFDsO1HtSPGiXXtvpmWGm4wXBYVA_8jTm39QSioP4wla9vg-Heqp_fKGyzntAwERI-jzLgvIhddwXJKBlmnEbz0NL7lOxEp7_CN0mI7qNWEwGZfB
    APP_ID=anllfcfmhljbgbiiedpfibjfboehhmhb

    curl \
    -o eve-test.zip https://codeload.github.com/Resetyo/eve-test/zip/master

    curl \
    -H "Authorization: Bearer $TOKEN"  \
    -H "x-goog-api-version: 2" \
    -X PUT \
    -T eve-test.zip \
    -v \
    https://www.googleapis.com/upload/chromewebstore/v1.1/items/$APP_ID

    curl \
    -H "Authorization: Bearer $TOKEN"  \
    -H "x-goog-api-version: 2" \
    -H "Content-Length: 0" \
    -X POST \
    -v \
    https://www.googleapis.com/chromewebstore/v1.1/items/$APP_ID/publish
  displayName: 'publish extension'
